#pragma once

#define CLI_COLOR_RED     "\x1b[31m"
#define CLI_COLOR_GREEN   "\x1b[32m"
#define CLI_COLOR_YELLOW  "\x1b[33m"
#define CLI_COLOR_BLUE    "\x1b[34m"
#define CLI_COLOR_MAGENTA "\x1b[35m"
#define CLI_COLOR_CYAN    "\x1b[36m"
#define CLI_COLOR_WHITE   "\x1b[37m"
#define CLI_COLOR_BRIGHT_RED     "\x1b[91m"
#define CLI_COLOR_BRIGHT_GREEN   "\x1b[92m"
#define CLI_COLOR_BRIGHT_YELLOW  "\x1b[93m"
#define CLI_COLOR_BRIGHT_BLUE    "\x1b[94m"
#define CLI_COLOR_BRIGHT_MAGENTA "\x1b[95m"
#define CLI_COLOR_BRIGHT_CYAN    "\x1b[96m"
#define CLI_COLOR_BRIGHT_WHITE   "\x1b[97m"

#define CLI_COLOR_RESET     "\x1b[0m"
#define CLI_COLOR_BOLD      "\x1b[1m"
#define CLI_COLOR_UNDERLINE "\x1b[4m"
#define CLI_COLOR_REVERSED  "\x1b[7m"
